### ISSUE TITLE
More regions

### ISSUE THREAD

**Issue by VinothMathi** [Martin91/paperclip-storage-aliyun#22]
Can you add all the available data centers to the gem?

**Comment by Martin91** [comment]
@VinothMathi thanks for pointing out the legacy data centers list, I have updated and released a new version https://github.com/Martin91/paperclip-storage-aliyun/commit/c7cc591dd94234e4269d27286342519e1a54ce0d, but currently I am not using my personal laptop so that I am unable to release to rubygems.org, instead, you can install it from GitHub.

**Comment by VinothMathi** [comment]
@Martin91 Thanks you so much.
